name: Update
on:
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: GetTime
      run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV
    - name: IPTV Source Update
      run: |
        rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
        sed -i -n '/央视频道/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u
        rm -f CNTV.m3u && touch CNTV.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/数字频道/,+1p' CNTV2.m3u
        cat CNTV1.m3u >> CNTV.m3u
        cat CNTV2.m3u >> CNTV.m3u
        rm -f CNTV1.m3u CNTV2.m3u
        sed -i '1i #EXTM3U' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u
        rm -f IPTV.m3u && touch IPTV.m3u
        cat CCTV.m3u >> IPTV.m3u
        cat CNTV.m3u >> IPTV.m3u
        rm -f CCTV.m3u CNTV.m3u
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated at ${{ env.DATE }}" && git push https://xiaoyan-io:${{ secrets.GH_TOKEN }}@github.com/xiaoyan-io/myiptv.git HEAD:main)
